name: saldodapenkujang
description: "Aplikasi saldo dana pensiun karyawan PT. Pupuk Kujang"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+3

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  http: any
  path_provider: ^2.0.15
  path_provider_android: ^2.0.27
  intl: ^0.19.0
  fl_chart: ^0.68.0
  flutter_html: ^3.0.0-beta.2
  crypto: ^3.0.1
#  image_picker: ^1.0.7
  flutter_pdfview: ^1.0.1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1  # Update to latest version

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"

flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
